### ISSUE TITLE
Failure running diagnostic_tools.py (on windows)

### ISSUE THREAD

**Issue by ittayd** [akamai-open/api-kickstart#6]
PS C:\Users\idror\Code\github\api-kickstart\examples\python> python .\diagnostic_tools.py

Requesting locations that support the diagnostic-tools API.

Traceback (most recent call last):
  File ".\diagnostic_tools.py", line 72, in <module>
    location_count = len(location_result['locations'])
KeyError: 'locations'

**Comment by maglietti** [comment]
I'm pretty sure that this is because there was an error returned rather then a locations object from the API call. Can you run the tool again with debugging enabled? (The easiest way to force debugging is to change line 11 from `debug = False` to `debug = True`)

If you are seeing an error in the debug output, verify that you have provisioned your credentials properly in Luna (enable Read access for the diagnostic tools API in the client authorization) and that you have properly transferred them to your .edgerc file. The `gen_edgerc.py` script can help you create the .edgerc file if you are not sure.

**Comment by maglietti** [comment]
Closing, ittayd didn't respond. Please reopen if you are still having this issue.
